### ISSUE TITLE
Peer-to-peer review 

### ISSUE THREAD

**Issue by anagudelogu** [latinogan/mobile4#4]
# Feedback :nerd_face:

Good job so far!
you could improve your code by having this in mind:
1. Remember to not leave any empty code in your HTML, this will help you with the general performance of your project and will keep your code clean and easy to read.
2. You could use more descriptive class names, so it makes reading your code smoother and gives useful information for those who read it.
3. Watch out for your indentation! remember to use 2 spaces just so you can make your code tidier and nice looking.

Happy coding!

**Comment by latinogan** [comment]
thanks
